version: "3.8"

services:
  web:
    container_name: django
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
    restart: on-failure

  db:
    container_name: postgresql
    image: postgres:13.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=tattoogen
      - POSTGRES_PASSWORD=tattoogen
      - POSTGRES_DB=tattoogen_dev
    restart: on-failure

volumes:
  postgres_data: