version: '3.8'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn tattoogen.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static/
      - ./storage:/home/app/web/storage/
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    restart: on-failure
  db:
    image: postgres:13.0
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env.prod.db
    restart: always
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static/
      - ./storage:/home/app/web/storage/
    ports:
      - 80:80
    depends_on:
      - web
    restart: on-failure

  redis:
    image: redis
    restart: always

  celery_worker:
    build: ./
    command: celery -A tattoogen worker -l info
    volumes:
      - .:/home/app/web
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - redis

  celery_beat:
    build: ./
    command: celery -A tattoogen beat -l info
    volumes:
      - .:/home/app/web
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - redis

volumes:
  static_volume:
